// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: task/service.proto

package task

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ListTaskResp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ListTaskResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListTaskResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ListTaskRespMultiError, or
// nil if none found.
func (m *ListTaskResp) ValidateAll() error {
	return m.validate(true)
}

func (m *ListTaskResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	switch v := m.Resp.(type) {
	case *ListTaskResp_Data_:
		if v == nil {
			err := ListTaskRespValidationError{
				field:  "Resp",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetData()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListTaskRespValidationError{
						field:  "Data",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListTaskRespValidationError{
						field:  "Data",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListTaskRespValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *ListTaskResp_Error:
		if v == nil {
			err := ListTaskRespValidationError{
				field:  "Resp",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetError()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListTaskRespValidationError{
						field:  "Error",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListTaskRespValidationError{
						field:  "Error",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetError()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListTaskRespValidationError{
					field:  "Error",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return ListTaskRespMultiError(errors)
	}

	return nil
}

// ListTaskRespMultiError is an error wrapping multiple validation errors
// returned by ListTaskResp.ValidateAll() if the designated constraints aren't met.
type ListTaskRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListTaskRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListTaskRespMultiError) AllErrors() []error { return m }

// ListTaskRespValidationError is the validation error returned by
// ListTaskResp.Validate if the designated constraints aren't met.
type ListTaskRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListTaskRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListTaskRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListTaskRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListTaskRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListTaskRespValidationError) ErrorName() string { return "ListTaskRespValidationError" }

// Error satisfies the builtin error interface
func (e ListTaskRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListTaskResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListTaskRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListTaskRespValidationError{}

// Validate checks the field values on ListTaskResp_Data with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListTaskResp_Data) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListTaskResp_Data with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListTaskResp_DataMultiError, or nil if none found.
func (m *ListTaskResp_Data) ValidateAll() error {
	return m.validate(true)
}

func (m *ListTaskResp_Data) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetTasks() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListTaskResp_DataValidationError{
						field:  fmt.Sprintf("Tasks[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListTaskResp_DataValidationError{
						field:  fmt.Sprintf("Tasks[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListTaskResp_DataValidationError{
					field:  fmt.Sprintf("Tasks[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetPageMetaData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListTaskResp_DataValidationError{
					field:  "PageMetaData",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListTaskResp_DataValidationError{
					field:  "PageMetaData",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPageMetaData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListTaskResp_DataValidationError{
				field:  "PageMetaData",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListTaskResp_DataMultiError(errors)
	}

	return nil
}

// ListTaskResp_DataMultiError is an error wrapping multiple validation errors
// returned by ListTaskResp_Data.ValidateAll() if the designated constraints
// aren't met.
type ListTaskResp_DataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListTaskResp_DataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListTaskResp_DataMultiError) AllErrors() []error { return m }

// ListTaskResp_DataValidationError is the validation error returned by
// ListTaskResp_Data.Validate if the designated constraints aren't met.
type ListTaskResp_DataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListTaskResp_DataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListTaskResp_DataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListTaskResp_DataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListTaskResp_DataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListTaskResp_DataValidationError) ErrorName() string {
	return "ListTaskResp_DataValidationError"
}

// Error satisfies the builtin error interface
func (e ListTaskResp_DataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListTaskResp_Data.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListTaskResp_DataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListTaskResp_DataValidationError{}
